### PR TITLE
Remove uses of reserved word arguments

### LINKED ISSUE #46: Assigning arguments causes build error
The declaration of `var arguments` causes a build error because it is a strict violation.

https://github.com/omniscientjs/immstruct/blob/master/src/structure.js#L453

`Module build failed: SyntaxError: /Users/frederickf/Programming/react-d3/node_modules/immstruct/src/structure.js: Binding arguments in strict mode (260:6)`

### PR DESCRIPTION
**Pull request by frederickfogerty**
Closes #46

### CODE REVIEW

**Comment by Dashed** [comment]
Wondering if it's worth inserting `'use strict';` like this guy does for all of his npm modules: https://github.com/sindresorhus

**Comment by frederickfogerty** [comment]
Browserify can do that for you, I think. 

https://www.npmjs.com/package/strictify

Alternatively you can do it manually

**Comment by mikaelbr** [comment]
Good change! Some how 'var arguments' slipped our review.

**Comment by frederickfogerty** [comment]
@mikaelbr you could use `info.args`, and initially I just changed the variable internal to the function, but then decided that it's just good practice not to use `arguments` when it's not referencing the reserved word `arguments`, and so changed the other occurrences of the property/word.

**Comment by mikaelbr** [comment]
Yeah, I agree.

**Pull request merged**
