### PR TITLE
Fix errors in api.md

### PR DESCRIPTION
**Pull request by leonyu**

### CODE REVIEW

**Comment by mikaelbr** [comment]
Hi. Thanks for the PR and fix, but the apm.md is actually generated from the jsdocs in the files. If you could update the source code instead (e.g. [here](https://github.com/omniscientjs/immstruct/blob/master/index.js#L62)), I'd be happy to merge.

**Comment by leonyu** [comment]
Done. 

Also having to read into JSDoc documentation, it appears following can be updated: 

* Array can be typed further
* the convention to use lower case `boolean`, `string`, `number` and `void` for primitive types. 

Do you want me to update those as well? I could do as separate PR. 

References: 
* http://usejsdoc.org/tags-type.html
* https://developers.google.com/closure/compiler/docs/js-for-compiler#types
* http://eslint.org/docs/rules/valid-jsdoc.html#requirereturn

P.S. This came out of my working on creating a [TypeScript definition](https://github.com/leonyu/DefinitelyTyped/tree/immstruct/immstruct) for this project.

**Comment by mikaelbr** [comment]
@leonyu Cool. Sure, you can just update this PR as it's more about correcting the jsdocs rather than the api.md. So I think it's fitting for this PR.

Funny you should do this now, I've been thinking of doing the same thing after researching different transpilation languages (thereof funscript and typescript). Perfect timing :cake: :+1:

**Comment by leonyu** [comment]
I left `Void` alone, cause Dox generates empty string in the markdown when I put `void` or `undefined`, which I felt was less desirable. Should be good.

**Comment by mikaelbr** [comment]
Great job. Merging now. :+1:

**Pull request merged**
