### PR TITLE
Use immutable-cursor

### LINKED ISSUE #89: immutable-js/contrib/cursor has been deprecated
immutable-js/contrib/cursor has been [deprecated](https://github.com/facebook/immutable-js/blob/master/contrib/cursor/README.md).

Suggest forking it, or replacing contrib/cursor with something from userland.

### PR DESCRIPTION
**Pull request by neftaly**
Fixes #89

### CODE REVIEW

**Comment by neftaly** [comment]
@mikaelbr any idea how to view the logs on Travis? It's not showing me anything

**Comment by mikaelbr** [comment]
Thanks. Good job 👍

**Comment by mikaelbr** [comment]
@neftaly In what way does `immutable-cursor` change it's API? Would this be a minor release or major?

**Comment by mikaelbr** [comment]
Thinking more about it, this would be a breaking change as we now rely on polyfilled `Object.assign`

**Comment by ZebraFlesh** [comment]
What's the timeframe for releasing this change?

**Comment by mikaelbr** [comment]
I'll look into it next week.

**Pull request merged**
